name: Continuous Integration
on:
  pull_request
  push:
    branches: [main, develop]
jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Analyze code
        run: bundle exec rubocop
  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Analyze code
        uses: artplan1/brakeman-action@v1.2.1
        with:
          flags: "--color"